export global AppConfig {
// ? Background colors
    out property <color> background: #141937; //* Задний фон.
    out property <color> surface_card: #2a3254; //* Карточки сообщений, панели.
    out property <color> surface_elevated: #2a3254; //* Приподнятые элементы, input-поля.
    out property <color> primary_accent: #eef2ff; //* CTA-кнопки, активные элементы.
    out property <color> secondary_accent: #979fba; //* Иконки, подсказки, второстепенные действия.

// ? Text colors
    out property <color> text_primary: #ffffff; //* Основной текст
    out property <color> text_secondary: #979fba; //*	Метки времени, имена, плейсхолдеры
    out property <color> active: #eef2ff; //* Статус онлайн, успех доставки.
    out property <color> Warning: #C99B40; //* LoRa-сигнал, предупреждения.
    out property <color> error: #B54A3A; //* Ошибка шифрования, разрыв соединения.
    out property <color> ble_indicator: #ffffff; //* BLE-статус (намеренно синий — контраст к зелёному).
    out property <color> divider: #1f253f; //* Разделители, обводки.


// ? Размеры
    //* Chat list
    // Main block
    in-out property <length> max_chat_list_width: 500px;
    in-out property <length> min_chat_list_height: 600px;
    in-out property <length> min_chat_list_width: 50px;
    in-out property <length> min_chat_list_collapsed_width: 60px;
    in-out property <length> max_chat_list_collapsed_width: 60px;
    in-out property <length> min_chat_list_not_collapsed_width: 200px;
    in-out property <length> max_chat_list_not_collapsed_width: 500px;
    in-out property <length> preferred_chat_list_width: 300px;
    
    // Header
    in-out property <length> chat_list_header_height: 50px;
    in-out property <length> chat_list_header_preferred_width: 200px;

    // Search
    in-out property <length> chat_list_header_search_height: 35px;
    in-out property <length> chat_list_header_search_border_radius: 17.5px;
    in-out property <length> chat_list_header_search_text_input_x: 25px;
    in-out property <length> chat_list_header_search_image_width: 20px;
    in-out property <length> chat_list_header_search_image_height: 20px;
    in-out property <length> chat_list_header_search_padding_horizontal: 12.5px;
    in-out property <length> chat_list_header_search_font_size: 12px; // Text - size
    in-out property <length> chat_list_header_search_height_difference: 42.5px;
    in-out property <length> chat_list_header_search_image_width_difference: 40px;
    
}
