import { AppConfig } from "../../config/app-config.slint";
import { ChatHeader } from "chat-header.slint";

export component ChatList {
    in property <length> window_height: 700px;
    in property <bool> collapsed: false;
    

    min-height: AppConfig.min_chat_list_height;
    min-width: root.collapsed ? 60px : 200px;
    max-width: root.collapsed ? 60px : 500px;

    VerticalLayout {
        ChatHeader {
            min-width: root.collapsed ? 60px : 200px;
            max-width: root.collapsed ? 60px : 500px;
            collapsed: root.collapsed;
            search-clicked => {
                // todo обработка нажатия лупы в свёрнутом режиме
            }
        }

        Rectangle {
            background: AppConfig.surface_card;
            height: window_height - AppConfig.chat_list_header_height;
            // todo здесь будут остальные элементы списка чатов
        }
    }
}