import { AppConfig } from "../../config/app-config.slint";

export component Search inherits Rectangle {
    in-out property <length> text_input_width: root.width - 60px;
    in-out property <string> search_text: "";
    
    in property <bool> collapsed: false;

    callback search-clicked();
    callback text-changed(string);

    if collapsed: TouchArea {
        width: 60px;
        height: parent.height;
        clicked => { root.search-clicked(); }

        Image {
            height: AppConfig.chat_list_header_search_image_height;
            width: AppConfig.chat_list_header_search_image_width;
            vertical-alignment: center;
            source: @image-url("../icons/search.svg");
        }
    }

    if !collapsed: HorizontalLayout {
        width: parent.width;
        Rectangle {
            width: text_input_width;
            clip: true;
            TextInput {
                x: AppConfig.chat_list_header_search_text_input_x;
                width: text_input_width;
                color: AppConfig.text_primary;
                vertical-alignment: center;
                font-size: AppConfig.chat_list_header_search_font_size;
                
                text <=> root.search_text;

                edited => {
                    root.text-changed(self.text);
                }
            }

            if root.search_text == "": Text {
                x: AppConfig.chat_list_header_search_text_input_x;
                font-size: AppConfig.chat_list_header_search_font_size;
                width: text_input_width;
                text: "Поиск...";
                color: AppConfig.text_secondary;
            }
        }
        Rectangle {
            Image {
                x: parent.width - AppConfig.chat_list_header_search_image_width_difference;
                height: AppConfig.chat_list_header_search_image_height;
                width: AppConfig.chat_list_header_search_image_width;
                source: @image-url("../icons/search.svg");
            }
        }
    }
}

export component ChatHeader inherits Rectangle {
    in-out property <string> search_text: "";

    in property <bool> collapsed: false;
    in property <length> parent_width;
    
    property <length> search_y: root.height - AppConfig.chat_list_header_search_height_difference;
    
    callback search-clicked();
    callback text-changed(string);
    
    height: AppConfig.chat_list_header_height;
    background: AppConfig.background;
    

    HorizontalLayout {
        padding-left: AppConfig.chat_list_header_search_padding_horizontal;
        padding-right: AppConfig.chat_list_header_search_padding_horizontal;
        Search {
            y: root.search_y;
            height: AppConfig.chat_list_header_search_height;
            border-radius: AppConfig.chat_list_header_search_border_radius;
            background: AppConfig.surface_card;
            collapsed: root.collapsed;

            search_text <=> root.search_text;

            search-clicked => { root.search-clicked(); }
            text-changed(t) => { root.text-changed(t); }
        }
    }
}