import { ChatList } from "components/chat-list/chat-list.slint";
import { AppConfig } from "config/app-config.slint";
import { TitleBar } from "components/title-bar.slint";

export component AppWindow inherits Window {
    in-out property <string> search_text: "";   
    
    property <length> chat_list_width: AppConfig.preferred_chat_list_width;
    property <bool> chat_list_collapsed: chat_list_width < AppConfig.min_chat_list_not_collapsed_width;
    
    background: AppConfig.secondary_accent;
    title: "Hollow";
    icon: @image-url("icons/logo-minimal.svg");
    callback text-changed(string);
    callback search-clicked();

    VerticalLayout {

        HorizontalLayout {
            spacing: 0px;

            ChatList {
                width: root.chat_list_width;
                collapsed: root.chat_list_collapsed;
                window_height: root.height;

                search_text <=> root.search_text;

                text-changed(t) => { root.text-changed(t); }
                search-clicked => {
                    root.chat_list_width = 300px;
                }
            }

            Rectangle {
                width: 3px;
                background: AppConfig.divider;

                TouchArea {
                    moved => {
                        chat_list_width = max(
                            AppConfig.min_chat_list_collapsed_width,
                            min(AppConfig.max_chat_list_width, chat_list_width + self.mouse-x - self.pressed-x)
                        );

                        if chat_list_width <= AppConfig.min_chat_list_not_collapsed_width {
                            chat_list_width = AppConfig.min_chat_list_collapsed_width;
                        }
                    }
                }
            }

            Rectangle {
                horizontal-stretch: 1;
                background: AppConfig.background;
                min-width: 400px;
                // todo ... контент
            }
        }
    }
    
}